### PR TITLE
Add command to auto start browser in webui

### PR DESCRIPTION
**Pull request by niafrond**
Automatically launch default browser with WEBUI URL when using windows.

### CODE REVIEW

**Comment by marian-m12l** [comment]
Hi,
Thanks for the contribution! I'd been thinking about this.
I'll have a look and try to make this work on all supported OSes before I merge.

**Comment by niafrond** [comment]
Hello !

You're welcome ! 

I've updated my branch with command for unix (tested on Ubuntu 19.04).
I don't have a Mac so I can help for the last one.

Your work is incredibly great, by the way !

**Comment by marian-m12l** [comment]
Thanks!
The merge will have to wait, though, as I'm working on another branch.
Why did you add the 10 seconds delay on unix only?

**Comment by niafrond** [comment]
When the browser is launched automatically, building is sometimes not finished : adding 10 second delay will prevent some computers to have a 404 page.
It's not applicable to Chrome which automatically refresh page when available.

**Comment by marian-m12l** [comment]
Thanks. I'm adding this feature directly into the java server, to avoid this issue. But thanks for the contribution anyway!!

**Pull request closed without merging**
